unique_ids:
  assets:
    standard-page.html: 6LZOO2RD4VG4Q3HBW7AKBPVE7QRIRXUK
    theme.css: 2TQFETHFFBA7BQBZ3GSHOQUJH73FBIK5
  forms:
    Form1: F6I7SQAFVHHU2APUIYOBFBPKNZPQNTFO
  modules: {}
  scripts: {}
  server_modules: {}
