unique_ids:
  assets:
    standard-page.html: RJDATLL75WREVJJBL27AE6D773QAEYM5
    theme.css: VPV7M5YKDBM6VP6DETFLDHZJ3Z5EDOBG
  forms:
    Form1: 3ORN4L27ZGLBW5QAF2AMQY23OOPBRCXF
    MijnAnvilForm: '17417044128026982279697.671956'
  modules: {}
  scripts: {}
  server_modules: {}
